#! /bin/sh

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i
# bspc monitor DVI-I-1 -d 1 2 3 4 5
# bspc monitor HDMI-1 -d 6 7 8 9 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
panel &
